# You can change these
url: http://addama.github.io
repo: https://github.com/addama/addama.github.io
title: Xtract Solutions Documentation Site
use_reading_time: false
use_category_listing: true
lazy_person_title: Lazy Person

# You should not change these
plugins:
 - jekyll-mentions
 - jemoji

permalink: /:categories/:title
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    default_lang: js
    span:
      disable: false
    block:
      line_numbers: true
      start_line: 1