url: "addama.github.io"
title: "Xtract Solutions Documentation"
permalink: /:categories/:title
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    default_lang: js
    span:
      disable: false
    block:
      line_numbers: true
      start_line: 1
      
# Custom props
use_reading_time: false
lazy_person_title: Lazy Person