url: "addama.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Xtract Solutions Documentation" # the name of your site, e.g. ACME Corp.

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    default_lang: js
    span:
      disable: false
    block:
      line_numbers: true
      start_line: 1